# Generated by Django 3.2.8 on 2021-11-06 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_parent_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='adress',
            new_name='address',
        ),
    ]
