# Generated by Django 3.2.8 on 2021-11-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20211106_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='postal_code',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
