# Generated by Django 3.2.8 on 2021-11-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_adress_extenduser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='phone',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extenduser',
            name='postal_code',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
